/**
 * Dicionário de apelidos → nomes completos possíveis
 * Chaves normalizadas: lowercase, sem acento, sem espaços extras
 */
export const NICKNAME_TO_FULL_NAMES: Record<string, string[]> = {
  "beto": ["Roberto", "Alberto", "Humberto", "Gilberto"],
  "ro": ["Roberto", "Rodrigo", "Rogério", "Rômulo"],
  "roger": ["Rogério"],
  "rogerio": ["Rogério"],
  "robi": ["Roberto"],
  "robinho": ["Roberto"],
  "caco": ["Carlos"],
  "ca": ["Carlos", "Carla", "Carolina", "Camila"],
  "cadu": ["Carlos Eduardo", "Eduardo"],
  "carlim": ["Carlos"],
  "carlinhos": ["Carlos"],
  "caca": ["Carlos", "Carolina", "Carla"],
  "dudu": ["Eduardo", "Eduarda"],
  "du": ["Eduardo", "Eduarda"],
  "ed": ["Eduardo", "Edson", "Edgar"],
  "eddy": ["Eduardo", "Edson"],
  "edinho": ["Edson"],
  "gui": ["Guilherme", "Guilhermina"],
  "guiga": ["Guilherme"],
  "guigo": ["Guilherme"],
  "guil": ["Guilherme"],
  "guga": ["Gustavo", "Augusto"],
  "gus": ["Gustavo", "Augusto"],
  "gut": ["Gustavo"],
  "guto": ["Augusto", "Gustavo"],
  "gutinho": ["Augusto", "Gustavo"],
  "leo": ["Leonardo", "Leandro", "Leonel"],
  "lele": ["Leonardo", "Letícia", "Helena"],
  "leozinho": ["Leonardo"],
  "leandrinho": ["Leandro"],
  "lu": ["Luiz", "Luis", "Lucas", "Luciano", "Lúcia", "Luciana", "Luana"],
  "luh": ["Luiz", "Luis", "Lucas", "Luciano", "Lúcia", "Luciana", "Luana"],
  "luca": ["Lucas", "Luca"],
  "luk": ["Lucas", "Lucca"],
  "lukas": ["Lucas"],
  "lulu": ["Luiz", "Luis", "Lucas", "Luciana", "Lúcia", "Luana"],
  "ma": ["Marcelo", "Marcos", "Maria", "Mariana", "Márcia"],
  "marcelo": ["Marcelo"],
  "marcelinho": ["Marcelo"],
  "marquinho": ["Marcos"],
  "marquinhos": ["Marcos"],
  "marcao": ["Marcos", "Marcelo"],
  "misa": ["Misael"],
  "mico": ["Miguel"],
  "migs": ["Miguel"],
  "miguelito": ["Miguel"],
  "nando": ["Fernando", "Fernanda"],
  "fe": ["Fernando", "Fernanda", "Felipe"],
  "fefe": ["Felipe", "Fernanda", "Fernando"],
  "felipinho": ["Felipe"],
  "lipi": ["Felipe"],
  "lipe": ["Felipe"],
  "phil": ["Filipe", "Felipe"],
  "jo": ["João", "José", "Joaquim", "Joana", "Joice"],
  "joaozinho": ["João"],
  "joca": ["Joaquim", "João Carlos"],
  "ze": ["José"],
  "zezinho": ["José"],
  "zeca": ["José"],
  "zeze": ["José"],
  "joe": ["João", "José"],
  "juninho": ["Junior", "Júnior"],
  "jr": ["Junior", "Júnior"],
  "kaio": ["Caio"],
  "kai": ["Caio"],
  "caique": ["Cauã", "Caíque"],
  "caua": ["Cauã"],
  "kaua": ["Cauã"],
  "rafa": ["Rafael", "Rafaela"],
  "rafinha": ["Rafael"],
  "rafaelzinho": ["Rafael"],
  "rafs": ["Rafael", "Rafaela"],
  "rick": ["Ricardo", "Henrique", "Eric"],
  "ricky": ["Ricardo"],
  "ric": ["Ricardo", "Henrique", "Eric"],
  "ricao": ["Ricardo"],
  "ricardinho": ["Ricardo"],
  "thi": ["Thiago", "Tiago"],
  "th": ["Thiago", "Tiago"],
  "ti": ["Thiago", "Tiago"],
  "tico": ["Thiago", "Tiago"],
  "thigas": ["Thiago"],
  "tiaguinho": ["Thiago", "Tiago"],
  "vini": ["Vinícius"],
  "vinny": ["Vinícius"],
  "vic": ["Victor", "Vitória", "Vicente"],
  "vitinho": ["Victor"],
  "vi": ["Vinícius", "Victor", "Vitória", "Viviane"],
  "xande": ["Alexandre"],
  "alex": ["Alexandre", "Alexandra", "Alexia"],
  "ale": ["Alexandre", "Alessandro", "Aline", "Alessandra"],
  "leko": ["Alexandre", "Leandro"],
  "sandro": ["Alessandro", "Alexandre"],
  "ton": ["Antônio", "Antonio"],
  "toni": ["Antônio", "Antonio", "Antônia"],
  "tonho": ["Antônio", "Antonio"],
  "toin": ["Antônio", "Antonio"],
  "totonho": ["Antônio", "Antonio"],
  "pa": ["Paulo", "Paula", "Patrícia"],
  "paulinho": ["Paulo"],
  "paulao": ["Paulo"],
  "pe": ["Pedro"],
  "pedrinho": ["Pedro"],
  "peu": ["Pedro"],
  "bruno": ["Bruno"],
  "bru": ["Bruno", "Bruna"],
  "bruninho": ["Bruno"],
  "dan": ["Daniel", "Danilo", "Daniele", "Daniela"],
  "dani": ["Daniel", "Daniela", "Daniele"],
  "danzinho": ["Daniel"],
  "niel": ["Daniel"],
  "samu": ["Samuel", "Samara"],
  "samuca": ["Samuel"],
  "sam": ["Samuel", "Samara", "Samantha"],
  "henri": ["Henrique"],
  "henry": ["Henrique"],
  "rique": ["Henrique"],
  "riq": ["Henrique"],
  "kike": ["Henrique"],
  "mat": ["Mateus", "Matheus", "Matias"],
  "matt": ["Mateus", "Matheus"],
  "math": ["Matheus"],
  "teus": ["Mateus", "Matheus"],
  "theus": ["Matheus"],
  "jp": ["João Pedro", "José Paulo", "João Paulo"],
  "jc": ["João Carlos", "José Carlos"],
  "jv": ["João Victor", "José Victor", "João Vinícius"],
  "mv": ["Marco Vinícius", "Maria Vitória", "Mateus Vinícius"],
  "bia": ["Beatriz", "Bianca"],
  "bi": ["Beatriz", "Bianca"],
  "bibi": ["Beatriz", "Bianca", "Bruna"],
  "biazinha": ["Beatriz", "Bianca"],
  "gabi": ["Gabriela", "Gabrielle", "Gabriel"],
  "gab": ["Gabriela", "Gabrielle", "Gabriel"],
  "gabs": ["Gabriela", "Gabrielle", "Gabriel"],
  "gabizinha": ["Gabriela"],
  "duda": ["Eduarda", "Maria Eduarda"],
  "dudinha": ["Eduarda", "Maria Eduarda"],
  "leti": ["Letícia"],
  "tete": ["Letícia", "Teresa"],
  "mah": ["Maria", "Mariana", "Marília", "Maitê"],
  "mari": ["Maria", "Mariana", "Marília"],
  "mary": ["Maria", "Mariana"],
  "marih": ["Mariana", "Maria"],
  "ana": ["Ana"],
  "aninha": ["Ana"],
  "nina": ["Ana", "Marina", "Antonina"],
  "nana": ["Ana", "Mariana", "Fernanda"],
  "anoca": ["Ana"],
  "ju": ["Júlia", "Juliana", "Juliene", "Jussara", "Julio", "Júnior"],
  "juju": ["Júlia", "Juliana"],
  "juli": ["Júlia", "Juliana"],
  "juh": ["Júlia", "Juliana"],
  "jubs": ["Júlia", "Juliana"],
  "pri": ["Priscila", "Priscilla"],
  "prika": ["Priscila"],
  "prisca": ["Priscila"],
  "carol": ["Carolina", "Caroline"],
  "cah": ["Carla", "Carolina", "Camila"],
  "cami": ["Camila", "Camilla"],
  "camis": ["Camila", "Camilla"],
  "isa": ["Isabela", "Isabella", "Isadora", "Isaura"],
  "bela": ["Isabela", "Isabella", "Gabriela"],
  "belinha": ["Isabela", "Isabella"],
  "nati": ["Natália", "Nathália"],
  "nathy": ["Natália", "Nathália"],
  "nat": ["Natália", "Nathália"],
  "tata": ["Tatiane", "Natália", "Tainá"],
  "thay": ["Thaís", "Thais", "Thaynara"],
  "tai": ["Thaís", "Tainá", "Taiane"],
  "tatah": ["Tatiane", "Tainá"],
  "manu": ["Manuela", "Emanuelle", "Manoela"],
  "manuzinha": ["Manuela"],
  "ema": ["Emanuelle", "Emanuela"],
  "fefa": ["Fernanda"],
  "nanda": ["Fernanda"],
  "nandinha": ["Fernanda"],
  "dri": ["Adriana", "Adriane", "Adrielly"],
  "drih": ["Adriana", "Adriane"],
  "adri": ["Adriana", "Adriane"],
  "lari": ["Larissa"],
  "lala": ["Larissa", "Laura", "Laila"],
  "larinha": ["Larissa"],
  "bel": ["Isabela", "Isabella", "Anabel", "Bela"],
  "bella": ["Isabela", "Isabella", "Bela"],
  "vivi": ["Viviane", "Vivian", "Vitória"],
  "vit": ["Vitória"],
  "vitoria": ["Vitória"],
  "rai": ["Raiane", "Raissa", "Raiany"],
  "raissa": ["Raissa"],
  "rah": ["Raiane", "Raissa", "Rafaela"],
  "aline": ["Aline"],
  "ali": ["Aline", "Alice"],
  "alice": ["Alice"],
  "lice": ["Alice"],
  "mih": ["Michele", "Micaela", "Milena"],
  "mi": ["Michele", "Milena", "Micaela", "Miriam"],
  "mimi": ["Michele", "Milena", "Miriam"],
  "kaka": ["Carlos", "Carla", "Karina", "Kátia"],
  "nene": ["Helena", "Ana", "José", "João"],
};
